WIP: Fixes footer styling/templates
az-digital/az_quickstart pull request #1013
Opened 2021-09-01 16:18 UTC by smayden

## Description

## Related Issue
#1012

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-08 23:43 UTC, trackleft commented on themes/custom/az_barrio/az_barrio.theme
> +      if(!empty($block) && $block->getRegion() === 'footer_sub') {
Could simplify with `if(!empty($block)` around both region checks.

2021-09-08 23:44 UTC, trackleft commented on themes/custom/az_barrio/config/optional/block.block.footerinformationfor.yml
> +id: footerinformationfor
change to `az_barrio_footer_menu_info`

2021-10-01 17:54 UTC, danahertzberg commented
Dana and Shoshana will determine styles needed for nav items. Troy will apply them with a preprocess function for the block in that region.

2021-10-19 23:22 UTC, smayden commented
@tadean @trackleft 
Any suggestions on how to get these items incorporated into this PR? 

- [ ] Sub footer area: Add d-flex px-0 to the li 
- [ ] In both footer and sub footer region - Set background area to transparent

2021-11-19 03:16 UTC, joshuasosa commented
> * [ ]  Sub footer area: Add d-flex px-0 to the li

In az_barrio_preprocess_block, this worked in my local testing:
```
foreach ($variables['elements']['content']['#items'] as $key => $item) {
  $variables['elements']['content']['#items'][$key]['attributes']->addClass('d-flex', 'px-0');
}
```

> * [ ]  In both footer and sub footer region - Set background area to transparent

Are you wanting to set link backgrounds to transparent? You can use the utility `.bg-transparent`

2021-12-03 15:55 UTC, tadean commented
@joshuasosa the following seemed to work well, thanks!
```
foreach ($variables['elements']['content']['#items'] as $key => $item) {
  $variables['elements']['content']['#items'][$key]['attributes']->addClass('d-flex', 'px-0');
}
```

2021-12-03 17:20 UTC, joeparsons commented on themes/custom/az_barrio/az_barrio.theme
> +        if($region === 'footer') {
Nitpick:
```suggestion
        if ($region === 'footer') {
```

2021-12-03 17:20 UTC, joeparsons commented on themes/custom/az_barrio/az_barrio.theme
> +        if($region === 'footer_sub') {
Nitpick:
```suggestion
        if ($region === 'footer_sub') {
```

2021-12-03 18:08 UTC, danahertzberg requested changes

2021-12-03 18:08 UTC, danahertzberg commented on themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_resources.yml
> +    classes: 'col-6 col-sm-4 col-md-2'
```suggestion
    classes: 'col-12 col-sm-6 col-md-2'
```

2021-12-03 18:08 UTC, danahertzberg commented on themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_topics.yml
> +    classes: 'col-12 col-sm-8 col-md-5'
```suggestion
    classes: 'col-12 col-sm-6 col-md-5'
```

2021-12-03 18:08 UTC, danahertzberg commented on themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_info.yml
> +    classes: 'col-12 col-sm-4 col-md-3'
```suggestion
    classes: 'col-12 col-sm-6 col-md-3'
```

2021-12-03 19:51 UTC, danahertzberg approved these changes
Muy bien!

2021-12-03 19:58 UTC, trackleft approved these changes

2021-12-03 22:04 UTC, merged