Closes #771: Use system branding block to support text-based web headers and more.
az-digital/az_quickstart pull request #1058
Opened 2021-09-27 23:04 UTC by joeparsons

## Description
This is an alternate PR for #771 adapted from @jwmoore1's #1054.

This approach embraces the system branding block added in D8 fully and does not add any additional theme settings to support text-based web headers.

Full list of changes:
- Fleshed out `block--system-branding-block.html.twig` with full support for logo, site name and site slogan
- Added a `branding` theme region
- Enabled system branding block in branding region (with only the logo enabled) by default
- Added site slogan to Quickstart settings page
- Replaced links to site information page in system branding block with links to Quickstart settings page
- Reverted some of @jwmoore1's changes to the theme settings, etc
- Added DB update to configure and enable branding block as well as new theme region settings on existing sites

## Related Issue
#771

## How Has This Been Tested?

Locally with lando.  DB update still needs testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-27 23:09 UTC, joeparsons commented on modules/custom/az_core/az_core.module
> + * Implements hook_form_BASE_FORM_ID_alter().
```suggestion
 * Implements hook_form_FORM_ID_alter().
```

2021-09-28 00:24 UTC, danahertzberg requested changes

2021-09-29 16:46 UTC, mmunro-ltrr commented
Trying a comparison of this and #1054. Having the branding block to display text headers gives easy access (just clicking on the usual pencil icon is enough). A potential source of confusion is the block title, since that's up at the top of the editing form, with a checkmark to enable the display (which works!), in addition to the options to display or enter the actual site title. The block display options are fully functional, & very powerful (you can do things like suppressing the site name display on selected content types). Looks good, but might need more documentation to prevent people doing weird things.

2021-09-29 17:44 UTC, camikazegreen approved these changes

2021-09-29 17:55 UTC, mmunro-ltrr submitted a review, later dismissed

2021-09-29 18:04 UTC, tadean submitted a review, later dismissed

2021-09-29 18:04 UTC, trackleft commented on az_quickstart.profile
> +    ->set('use_site_slogan', FALSE)
```suggestion
    ->set('settings.use_site_name', FALSE)
    ->set('settings.use_site_slogan', FALSE)
```

2021-09-29 18:07 UTC, joeparsons commented on modules/custom/az_core/az_core.module
> +      $site_name_description = t('Defined on the Quickstart settings page. You do not have the appropriate permissions to change the site logo.');
```suggestion
      $site_name_description = t('Defined on the Quickstart settings page. You do not have the appropriate permissions to change the site name.');
```

2021-09-29 18:07 UTC, joeparsons commented on modules/custom/az_core/az_core.module
> +      $site_slogan_description = t('Defined on the Quickstart settings page. You do not have the appropriate permissions to change the site logo.');
```suggestion
      $site_slogan_description = t('Defined on the Quickstart settings page. You do not have the appropriate permissions to change the site slogan.');
```

2021-09-29 18:39 UTC, trackleft approved these changes

2021-09-29 19:27 UTC, joeparsons commented
The database update seems to be working as expected now.

2021-09-29 19:28 UTC, trackleft approved these changes

2021-09-29 20:09 UTC, camikazegreen approved these changes

2021-09-29 20:09 UTC, mmunro-ltrr submitted a review, later dismissed

2021-09-29 20:12 UTC, smayden approved these changes

2021-09-29 20:25 UTC, danahertzberg commented on themes/custom/az_barrio/templates/blocks/block--system-branding-block.html.twig
> +      <span class="d-inline-block h3 text-blue text-uppercase bold my-3">{{ site_name }}</span>
```suggestion
      <span class="d-inline-block h3 text-blue text-uppercase bold my-4">{{ site_name }}</span>
```

2021-09-29 20:25 UTC, danahertzberg commented on themes/custom/az_barrio/templates/blocks/block--system-branding-block.html.twig
> +    <div class="d-inline-block align-top site-name-slogan lead mb-3">
```suggestion
    <div class="d-inline-block align-top site-name-slogan lead mb-4">
```

2021-09-29 21:05 UTC, danahertzberg approved these changes

2021-09-29 21:09 UTC, camikazegreen approved these changes

2021-09-29 21:09 UTC, mmunro-ltrr approved these changes

2021-09-29 21:10 UTC, merged