Replaced drush en with drush install
az-digital/az_quickstart pull request #2040
Opened 2022-11-02 22:40 UTC by ejsamboy

## Description
Replaced drush en with drush install

## Related issues
Closes #1695 

## Types of changes

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-11-02 23:08 UTC, joeparsons submitted a review, later dismissed
Looks good to me.  Thanks!

2022-11-02 23:39 UTC, bberndt-uaz commented
@ejsamboy It looks like there is one more instance of `pm:enable` on [line 108 in review-site.yml](https://github.com/az-digital/az_quickstart/blob/main/.github/workflows/review-site.yml#L108).

2022-11-04 17:07 UTC, trackleft approved these changes

2022-11-04 17:09 UTC, trackleft requested changes
[Additional instances ](https://github.com/az-digital/az_quickstart/pull/2040#issuecomment-1301494677)

2022-11-04 17:26 UTC, trackleft approved these changes

2022-11-04 17:40 UTC, bberndt-uaz approved these changes

2022-11-04 17:47 UTC, joeparsons approved these changes

2022-11-04 17:56 UTC, merged