Closes #2375 Adding Flag to Quickstart with Basic Permissions
az-digital/az_quickstart pull request #2376
Opened 2023-04-26 23:33 UTC by mrbeiley

## Description
Added administer flagging to Content Admin role. I also included the Flag module in the composer.json file - pinned to version 4.0-beta4.

## Related issues

Closes #2375 
Blocks #2323 

## How to test

Create new Flags, login as content admin.

## Types of changes

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [x] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [x] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-04-26 23:57 UTC, joshuasosa requested changes
I'm not sure about including Flag just yet. The module author has clear notices on the module page that it should not yet be used for production:

> Branch status
> 8.x-4.x: Under active development, but not yet ready for production.

> Flag 8.x-4.x is a complete rewrite of Flag module for Drupal 8. This version is not yet ready for production.

I don't like the idea of including a module enabled by default which the module authors themselves say is not ready for production. If anything, this module should _only_ be made available as an _option_.

2023-04-28 18:09 UTC, joeparsons commented on az_quickstart.info.yml
> +  - drupal:flag
Based on the discussion in our 2023-04-28 Friday meeting, it sounds like we don't want the module to be installed by default.
```suggestion
```

2023-04-28 18:21 UTC, mrbeiley commented
> I'm not sure about including Flag just yet. The module author has clear notices on the module page that it should not yet be used for production:
> 
> > Branch status
> > 8.x-4.x: Under active development, but not yet ready for production.
> 
> > Flag 8.x-4.x is a complete rewrite of Flag module for Drupal 8. This version is not yet ready for production.
> 
> I don't like the idea of including a module enabled by default which the module authors themselves say is not ready for production. If anything, this module should _only_ be made available as an _option_.

After reviewing the PR in today's Friday Meeting, we reached the same conclusion. Joe removed the Flag module from the default installations.

2023-05-03 17:12 UTC, trackleft approved these changes

2023-05-03 17:24 UTC, joeparsons approved these changes

2023-05-03 21:26 UTC, joshuasosa approved these changes

2023-05-10 18:26 UTC, merged