Closes #3597: Add lifecycle_link to experimental modules documentation in experimental modules.
az-digital/az_quickstart pull request #3598
Opened 2024-08-02 21:17 UTC by joeparsons

## Description

## Related issues

Closes #3597

## How to test

## Types of changes

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [x] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [ ] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

2024-08-02 21:47 UTC, trackleft approved these changes

2024-08-02 21:49 UTC, trackleft commented
Looks good
<img width="1628" alt="image" src="https://github.com/user-attachments/assets/38141e6e-571d-40ad-a150-5fad4b69ad77">

2024-08-02 23:15 UTC, trackleft approved these changes

2024-08-02 23:16 UTC, trackleft requested changes
We should also update the section that says how to classify a module as experimental.
https://github.com/az-digital/az_quickstart/blob/main/RELEASES.md#classifying-modules-as-experimental

2024-08-07 20:45 UTC, trackleft submitted a review, later dismissed

2024-08-09 16:29 UTC, bberndt-uaz commented on RELEASES.md
> +To classify a module as experimental, define the following properities in the module's `.info.yml` file:
```suggestion
To classify a module as experimental, define the following properties in the module's `.info.yml` file:
```

2024-08-09 16:40 UTC, trackleft approved these changes

2024-08-09 17:40 UTC, bberndt-uaz approved these changes

2024-08-09 17:41 UTC, tadean approved these changes

2024-08-09 17:48 UTC, merged