Schema.org Metatag "CollegeOrUniversity" issue/3644
az-digital/az_quickstart pull request #3743
Opened 2024-09-26 18:38 UTC by mrbeiley

## Description

Resolves https://github.com/az-digital/az_quickstart/issues/3644, adding a new module to the existing Schema.org Metatag modules. This module contains all the fields laid out in this [document](https://docs.google.com/document/d/1EPY0-2zrUXmTGR4o01GcRm_IhA9YZxlGsDJKBSjfc6M/edit?usp=sharing).

### Release notes

If this change requires release notes: provide a summary of changes, how to 
use this change, and any related links. This content will be pasted in the 
[release notes](https://github.com/az-digital/az_quickstart/releases). Use 
markdown format to ensure proper pasting of information.

Make sure to add the `release notes` label to this PR.

```
Add markdown of release notes here.
```

## Related issues

https://github.com/az-digital/az_quickstart/issues/3644 

## How to test

(on local, lando site)
- Install the 'Schema Metatag CollegeOrUniversity Final' module
- Open up a Page in the CKeditor
- Click the 'Metatags' dropdown
- Find the 'CollegeOrUniversity' dropdown
- Enter in sample fields and save the Page
- View the page and open the source code
- The Schema data should be displayed inside the "<script type=application/ld+json"> tag
- Verify Schema structure and data

## Types of changes

### Arizona Quickstart (install profile, custom modules, custom theme)
- **Patch release changes**
   - [ ] Bug fix
   - [ ] Accessibility, performance, or security improvement
   - [ ] Critical institutional link or brand change
   - [ ] Adding experimental module
   - [ ] Update experimental module
- **Minor release changes**
   - [ ] New feature
   - [ ] Breaking or visual change to existing behavior
   - [ ] Upgrade experimental module to stable
   - [ ] Enable existing module by default or database update
   - [ ] Non-critical brand change
   - [ ] New internal API or API improvement with backwards compatibility
   - [ ] Risky or disruptive cleanup to comply with coding standards
   - [ ] High-risk or disruptive change (requires upgrade path, risks regression, etc.)
- **Other or unknown**
   - [ ] Other or unknown

### Drupal core
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch level release (non-security bug-fix release)
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major or minor level update
- **Other or unknown**
   - [ ] Other or unknown

### Drupal contrib projects
- **Patch release changes**
   - [ ] Security update
   - [ ] Patch or minor level update
   - [x] Add new module
   - [ ] Patch removal that's no longer necessary
- **Minor release changes**
   - [ ] Major level update
- **Other or unknown**
   - [ ] Other or unknown

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change requires release notes.

2024-09-27 01:21 UTC, joshuasosa commented
Seems interesting but I was unable to test on the Probo site. The Schema.org CollegeOrUniversity Final module says "Requires: schema_metatag (missing)." Does schema_metatag need to be added as something that'll come packaged with AZQS or is it expected to need to include it in custom composer?

Besides that, it looks like this PR is adding a custom module. Other custom modules have a prefix of 'az_', which makes me think this one should similarly have that prefix.

2024-09-27 16:00 UTC, mrbeiley commented
> Seems interesting but I was unable to test on the Probo site. The Schema.org CollegeOrUniversity Final module says "Requires: schema_metatag (missing)." Does schema_metatag need to be added as something that'll come packaged with AZQS or is it expected to need to include it in custom composer?
> 
> Besides that, it looks like this PR is adding a custom module. Other custom modules have a prefix of 'az_', which makes me think this one should similarly have that prefix.

Yes it should have the 'az_' prefix, probably. As for the schema_metatag module, I don't know...

2024-09-27 17:58 UTC, mrbeiley commented
- Create an Issue to add the module to [Schema.org Metatag](https://www.drupal.org/project/issues/schema_metatag?status=All&categories=All). Are they interested in including this? Give at least a couple weeks to discuss it. Joe can help.
- Add 'az_' prefix to module
- Possibly add 'CollegeOrUniversity' [Property type](https://git.drupalcode.org/project/schema_metatag/-/tree/8.x-2.x/src/Plugin/schema_metatag/PropertyType?ref_type=heads)

2024-09-30 22:59 UTC, joshuasosa commented
Someone can correct me but I think you'd need to add schema_metatag to the [composer file](https://github.com/az-digital/az_quickstart/blob/main/composer.json) for this to be reviewable.

2024-11-19 16:58 UTC, RyanDool requested changes
It appears there is something incorrectly set for the parentOrganization [https://app.screencast.com/yRfwpPPntyR2I?conversation=Gu66Z71Efrv9SRKQJnabUc]

2024-11-21 00:16 UTC, joeparsons commented
Alternate PR that adds schema_metatag module and patch from d.o. issue/MR we have been working on:
#3901

2025-07-09 17:11 UTC, mrbeiley commented
Since #3901 is merged, going to close this one for now.

2025-07-09 17:11 UTC, closed without merging