initial news view and media list view mode for issue/130
az-digital/az_quickstart pull request #453
Opened 2021-01-20 17:01 UTC by smayden

Creating initial view for news matching the Media List Page (/news) in QS1

## Description
Draft pull request - still working on some issues:
- Token for short title not working
- Bootstrap classes for media list link missing
- Need image style crops needed

## Related Issue
#130 

## How Has This Been Tested?
Tested locally

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I've added this Pull Request to the AZ Quickstart project in the right column.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-01-20 20:38 UTC, danahertzberg commented
@smayden We could probably use the card crop for images for now. It could be a good idea to look at other classes that achieve a similar look and already exist (`card` perhaps?). And the token issue is a widespread D9 issue, right?

2021-01-21 22:08 UTC, trackleft requested changes

2021-01-21 22:08 UTC, trackleft commented on modules/custom/az_core/config/install/core.entity_view_mode.node.az_media_list.yml
> +cache: true
```suggestion
cache: true

```

2021-01-21 22:08 UTC, trackleft commented on modules/custom/az_news/az_news.info.yml
> +  - field_group_link
```suggestion
  - field_group_link
  
```

2021-01-21 23:53 UTC, danahertzberg approved these changes
This looks lovely!

2021-01-22 16:13 UTC, trackleft approved these changes

2021-01-22 16:46 UTC, joeparsons commented on composer.json
> -        "drupal/token": "1.7",
The sorting changes in this file may cause conflicts with other open PRs so we might want to consider merging this PR last today.

2021-01-22 17:01 UTC, smayden commented
Realized that stories were not going into URL /news so add pathauto settings

2021-01-22 17:34 UTC, tadean approved these changes

2021-01-22 17:41 UTC, camikazegreen commented on modules/custom/az_news/config/install/views.view.az_news.yml
> +      title: 'AZ News'
```suggestion
      title: 'News'
```

2021-01-22 17:44 UTC, danahertzberg commented
Minor nitpick: I would recommend removing the "Strong" field group to simplify. `psuedo-link` (misspelled) is not needed and we can move `strong` to the surrounding "Heading" field group.
![Screen Shot 2021-01-22 at 10 41 43 AM](https://user-images.githubusercontent.com/59745109/105525850-d995e680-5c9e-11eb-80f5-7f257cf0779d.png)

2021-01-22 18:25 UTC, camikazegreen approved these changes

2021-01-22 18:27 UTC, trackleft approved these changes

2021-01-22 18:28 UTC, tadean approved these changes

2021-01-22 18:32 UTC, merged