Add styling to event category taxonomy terms (Closes #727)
az-digital/az_quickstart pull request #758
Opened 2021-05-19 01:30 UTC by smayden

## Description

## Related Issue

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-05-21 22:31 UTC, danahertzberg requested changes

2021-05-21 22:31 UTC, danahertzberg commented on modules/custom/az_event/az_event.module
> +      $variables['items'][$key]['content']['#options']['attributes']['class'][] = 'badge badge-link badge-light float-left mr-2';
Recommend adding the `mb-2` class so there is space between them if they wrap. The `float-left` class ends up overriding this feature of the `badge` class.
```suggestion
      $variables['items'][$key]['content']['#options']['attributes']['class'][] = 'badge badge-link badge-light float-left mr-2 mb-2';
```

2021-05-21 23:00 UTC, smayden commented
Thanks for the suggestion @danahertzberg 

Committed your changes and things now wrap well on small screens

![image](https://user-images.githubusercontent.com/10873398/119205643-a21d2800-ba4d-11eb-8db6-88dee4865f35.png)

2021-05-21 23:50 UTC, danahertzberg approved these changes

2021-05-26 17:46 UTC, tadean approved these changes

2021-05-26 17:47 UTC, trackleft approved these changes

2021-05-26 17:48 UTC, danahertzberg commented
Ready to merge after security update

2021-05-26 21:57 UTC, merged